sudo: required
services:
  - docker

before_install:
  - docker build -t pnair1995/react-test -f ./client/Dockerfile.dev ./client 

script:
  - docker run -e CI=true pnair1995/react-test npm test

after_success:
  - docker build -t pnair1995/multi-client ./client
  - docker build -t pnair1995/multi-nginx ./nginx
  - docker build -t pnair1995/multi-server ./server
  - docker build -t pnair1995/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push pnair1995/multi-client
  - docker push pnair1995/multi-nginx
  - docker push pnair1995/multi-server
  - docker push pnair1995/multi-worker
  

